### ISSUE TITLE
Plover-Stenobee doesn't work

### ISSUE THREAD

**Issue by IQubic** [dnaq/plover-flake#217]
So, I'm trying to install `plover-stenobee` and it doesn't seem to be working. I think this is because stenobee relies on `plover-python-dictionary` and `inflect`. I'm not sure how to fix this on my own. Stenobee's code can be found here. https://github.com/Tink-Bell/StenoBee
```
error: builder for '/nix/store/8h3c0hnqs8db27lv025z2vwm21x5p9i4-python3.10-plover-stenobee-0.5.12.7.drv' failed with exit code 1;
       last 10 log lines:
       >
       >         ********************************************************************************
       >         Requirements should be satisfied by a PEP 517 installer.
       >         If you are using pip, you can try `pip install --use-pep517`.
       >         ********************************************************************************
       >
       > !!
       >   ir_d = dist.fetch_build_eggs(dist.install_requires)
       > /nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/bin/python3.10: No module named pip
       > error: Command '['/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/bin/python3.10', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmp1i1rchoz', '--quiet', 'plover-python-dictionary']' returned non-zero exit status 1.
       For full logs, run 'nix log /nix/store/8h3c0hnqs8db27lv025z2vwm21x5p9i4-python3.10-plover-stenobee-0.5.12.7.drv'.
error: 1 dependencies of derivation '/nix/store/d00kx739jk64jcrfc8fnpgg5v74ysf90-python3.10-plover-master.drv' failed to build
error: 1 dependencies of derivation '/nix/store/byg00w6qwwpigpsv5nahgmnacgkjl0if-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nn6mj65xyl2f86g10w42qdmkgkwhfkl8-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/g9d17kxrrn18cg7pnk1sl52hpvviz627-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/k925khb5d0f8ghjvky0jnv1rbn1y8cc3-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/h69r93drnswdspk0hrf30ankxb6nrq9x-nixos-system-LATITUDE-NIXOS-23.11.20231011.5e4c2ad.drv' failed to build
```

**Comment by toyboot4e** [comment]
I tried `plover.withPlugins (ps: [ps.plover-stenobee])`, but the build succeeded without modifying `overrides.nix` (somehow).

**Comment by toyboot4e** [comment]
Ah OK, the build succeeds, but there's some error print in terminal:

```
2025-06-25 23:52:55,928 [MainThread] ERROR: error loading meta plugin: pluralize (from stenobee.metas: k)
Traceback (most recent call last):
  File "/nix/store/k4j05gjh4gdbyx71hldg5ixmn3jnm5gz-python3.12-plover-master/lib/python3.12/site-packages/plover/registry.py", line 54, in register_plugin_from_entrypoint
    obj = entrypoint.load()
          ^^^^^^^^^^^^^^^^^
  File "/nix/store/f2krmq3iv5nibcvn4rw7nrnrciqprdkh-python3-3.12.9/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/f2krmq3iv5nibcvn4rw7nrnrciqprdkh-python3-3.12.9/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/nix/store/6rsfl2pgpgiscq2zizxk874jiq9865md-python3.12-plover-stenobee-0.8.24/lib/python3.12/site-packages/stenobee/metas.py", line 3, in <module>
    import inflect
ModuleNotFoundError: No module named 'inflect'
```

It would result in runtime error on [`pluralize`](https://github.com/Tink-Bell/StenoBee/blob/7e2db4dd1ba16e4c38a1beb6e41beaa188fa5bbe/stenobee/metas.py#L5). I'll fix it with `overrides.nix`.
